repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.2"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--output-format=full", "--line-length=250"]
        exclude: ^.*\.(ipynb)$
      - id: ruff-format
